#!/bin/bash

# Set variables
JAVA_VERSION="17"
PAPER_VERSION="1.20.4"
PAPER_BUILD="365"

# Download and extract Java
wget https://download.java.net/java/GA/jdk$JAVA_VERSION/$JAVA_VERSION/GPL/openjdk-$JAVA_VERSION_linux-x64_bin.tar.gz
tar -xzvf openjdk-$JAVA_VERSION_linux-x64_bin.tar.gz

# Set environment variables
export JAVA_HOME=$(pwd)/jdk-$JAVA_VERSION
export PATH=$JAVA_HOME/bin:$PATH

# Update the system alternatives
sudo update-alternatives --install /usr/bin/java java $JAVA_HOME/bin/java 1
sudo update-alternatives --install /usr/bin/javac javac $JAVA_HOME/bin/javac 1

# Download server JAR
SERVER_JAR_LINK="https://api.papermc.io/v2/projects/paper/versions/$PAPER_VERSION/builds/$PAPER_BUILD/downloads/paper-$PAPER_VERSION-$PAPER_BUILD.jar"
wget "$SERVER_JAR_LINK" -O server.jar

# Accept the Minecraft EULA
echo "eula=true" > eula.txt

# Modify server.properties
echo "online-mode=false" >> server.properties
echo "view-distance=4" >> server.properties
echo "simulation-distance=4" >> server.properties

# Set memory allocation
MEMORY_ALLOCATION="8G"

# Launch the Minecraft server
java -Xmx"$MEMORY_ALLOCATION" -Xms"$MEMORY_ALLOCATION" -jar server.jar nogui
